config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "recipes#search"

  resources :recipes, only: [:show] do
    collection do
      get 'search' # Defines /recipes/search path
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe

  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  SORT_BY = %w[rate nb_comments total_time].freeze

  has_many :recipe_tags
  has_many :tags, through: :recipe_tags

  has_many :ingredients, dependent: :destroy

  enum difficulty: { very_easy: 0, easy: 1, medium: 2, hard: 3 }  # trés facile, facile, Niveau moyen, difficile
  enum budget: { cheap: 0, normal: 1, expensive: 2 } # bon marché, Coût moyen, assez cher

  # These 2 enums could be extracted to 2 separate models with has_one association
  # but it will slow down search queries because of joins
  # we could consider it if these lists change often, need CRUD, or more details.

  validates :name, presence: true
  validates :budget, presence: true, inclusion: { in: budgets.keys }
  validates :difficulty, presence: true, inclusion: { in: difficulties.keys }

  scope :with_tags, -> (tag_ids) {
    joins(:tags)
      .where(tags: { id: tag_ids })
      .group('recipes.id')
      .having('COUNT(distinct tags.id) = ?', tag_ids.count)
  }

  scope :with_ingredients, ->(ingredient_names) {
    ingredient_names = ingredient_names.map { |name| "%#{name.downcase}%" }

    recipes = Recipe.joins(:ingredients)
      .where('lower(ingredients.name) ILIKE ANY (array[?])', ingredient_names)
      .group('recipes.id')
      .having('COUNT(DISTINCT ingredients.name) >= ?', ingredient_names.size)

    where(id: recipes.select('recipes.id'))
  }
end

app/models/recipe_tag.rb
# app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  belongs_to :recipe
  belongs_to :tag

  validates :tag_id, uniqueness: { scope: :recipe_id }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :recipe_tags
  has_many :recipes, through: :recipe_tags

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def show
    @recipe = Recipe.includes(:tags, :ingredients).find(params[:id])
  end

  def search
    @recipes = RecipeSearchService.new(params).call
    @recipe_search_form_presenter = RecipeSearchFormPresenter.new(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YourAppName</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
  <header>
    <!-- Bootstrap Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Pennylane Recipes book</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Search", search_recipes_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <main class="container mt-4">
    <%= yield %>
  </main>

  <footer class="footer mt-auto py-3 bg-light">
    <div class="container">
      <span class="text-muted">Place sticky footer content here.</span>
    </div>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/views/recipes/search.html.erb
<%= form_with(url: search_recipes_path, method: :get, local: true, class: "row g-3") do |f| %>
  <div class="col-md-6">
    <%= f.label :tag_ids, "Catégories", class: "form-label" %>
    <%= f.collection_select :tag_ids, @recipe_search_form_presenter.tags, :last, :first, { include_blank: true, selected: @recipe_search_form_presenter.selected_tags }, { multiple: true, class: "form-select" } %>
  </div>

  <div class="col-md-3">
    <%= f.label :name, "Nom de la recette", class: "form-label" %>
    <%= f.text_field :name, value: @recipe_search_form_presenter.selected_name, class: "form-control" %>
  </div>

  <div class="col-md-3">
    <%= f.label :ingredient_names, "Ingrédients", class: "form-label" %>
    <%= f.text_field :ingredient_names, value: @recipe_search_form_presenter.selected_ingredient_names, class: "form-control" %>
  </div>

  <div class="col-md-3">
    <%= f.label :budget, "Budget", class: "form-label" %>
    <%= f.select :budget, @recipe_search_form_presenter.budgets, { include_blank: true, selected: @recipe_search_form_presenter.selected_budget }, class: "form-select" %>
  </div>

  <div class="col-md-3">
    <%= f.label :difficulty, "Difficulté", class: "form-label" %>
    <%= f.select :difficulty, @recipe_search_form_presenter.difficulties, { include_blank: true, selected: @recipe_search_form_presenter.selected_difficulty }, class: "form-select" %>
  </div>

  <div class="col-md-3">
    <%= f.label :total_time, "Temps de préparation max. (minutes)", class: "form-label" %>
    <%= f.number_field :total_time, value: @recipe_search_form_presenter.selected_total_time, min: 0, step: 10, class: "form-control" %>
  </div>

  <div class="col-md-3">
    <%= f.label :sort_by, "Tri des résultats", class: "form-label" %>
    <%= f.select :sort_by, @recipe_search_form_presenter.sort_by, { include_blank: true, selected: @recipe_search_form_presenter.selected_sort_by }, class: "form-select" %>
  </div>

  <div class="col-12">
    <%= f.submit "Recherche", class: "btn btn-success" %>
  </div>
<% end %>

<div class="row row-cols-1 row-cols-md-4 g-4 mt-4">
  <% @recipes.each do |recipe| %>
    <div class="col">
      <div class="card h-100">
        <% if recipe.image.present? %>
          <%= image_tag recipe.image, class: "card-img-top" %>
        <% else %>
          <%= image_tag "https://via.placeholder.com/300x200", class: "card-img-top" %>
        <% end %>

        <div class="card-body">
          <h5 class="card-title"><%= recipe.name %></h5>
        </div>

        <!-- use decorator ? -->
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Note :
            <% if recipe.rate %>
              <%= number_with_precision(recipe.rate, precision: 2, strip_insignificant_zeros: true) %> / 5
            <% else %>
            aucune
            <% end %>
          </li>
          <li class="list-group-item">Nombre de commentaires : <%= recipe.nb_comments %></li>
          <li class="list-group-item">Temps de préparation : <%= ChronicDuration.output(recipe.total_time, :format => :short) %></li>
        </ul>

        <div class="card-body">
          <%= link_to "Voir la recette", recipe_path(recipe), class: "card-link btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= paginate @recipes %>

app/views/recipes/show.html.erb
<div class="container mt-4">
  <h1><%= @recipe.name %></h1>

  <% if @recipe.image.present? %>
    <%= image_tag @recipe.image, class: "img-fluid rounded" %>
  <% else %>
    <%= image_tag "https://via.placeholder.com/300x200", class: "img-fluid rounded" %>
  <% end %>

  <ul>
    <li><strong>Nombre de personnes :</strong> <%= @recipe.people_quantity %></li>
    <li><strong>Temps de préparation :</strong> <%= ChronicDuration.output(@recipe.prep_time, :format => :short) %></li>
    <li><strong>Temps de cuisson :</strong> <%= ChronicDuration.output(@recipe.cook_time, :format => :short) %></li>
    <li><strong>Temps total :</strong> <%= ChronicDuration.output(@recipe.total_time, :format => :short) %></li>
    <li><strong>Note :</strong> <%= number_with_precision(@recipe.rate, precision: 2, strip_insignificant_zeros: true) %> / 5</li>
    <li><strong>Nombre de commentaires :</strong> <%= @recipe.nb_comments %></li>
    <li><strong>Auteur :</strong> <%= @recipe.author %></li>
    <li><strong>Astuce de l'auteur :</strong> <%= @recipe.author_tip %></li>
  </ul>

  <% if @recipe.ingredients.any? %>
    <h2>Ingrédients</h2>
    <ul>
      <% @recipe.ingredients.each do |ingredient| %>
        <li><%= ingredient.name %></li>
      <% end %>
    </ul>
  <% end %>


  <% if @recipe.tags.any? %>
    <h2>Tags</h2>
    <ul>
      <% @recipe.tags.each do |tag| %>
        <li><%= tag.name %></li>
      <% end %>
    </ul>
  <% end %>

  <%= link_to 'Retour recherche', search_recipes_path, class: "btn btn-primary" %>
</div>